substitutions:
  name: "bewegingsensor-boonstra"
  friendly_name: "Beweging sensor Boonstra"
  hidden_ssid: "false"
  log_level: DEBUG

packages:
  device_base: !include common/bewegingsensor-boonstra-base.yaml
  ld2450_base: !include common/ld2450-base.yaml
  bme280_base: !include common/bme280-base.yaml
  bluetooth_base: !include common/bluetooth-base.yaml
